### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by rodolfodn** [hosein2398/gue#3]
Just installed this tool but I keep receiving this error.

┌──────────────────────────────────┐
│                                                                                         │
│   ⚠️ Oops something went wrong                                 │
│                                                                                         │
└──────────────────────────────────┘
Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (fs.js:823:3)
    at Gue.checkDirStatus (C:\Users\user\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:113:10)
    at Gue.writeComponent (C:\Users\user\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:35:10)
    at Gue.generate (C:\Users\user\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:27:10)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\vue-gue\src\bin.js:21:9)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT'
}

**Comment by hosein2398** [comment]
What command are you typing? it must be problem with dir which you are setting

**Comment by rodolfodn** [comment]
Just installed, went to any folder and typed 'gue foo'

node -v
v12.13.1

npm -v
6.13.1

windows 10

**Comment by hosein2398** [comment]
Ummm, I have no idea right now.
Does it work when you define path? like:
```
gue foo ./mydir/somewhere
```

**Comment by rodolfodn** [comment]
mkdir bar
> mkdir bar
> gue foo ./bar

Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (fs.js:823:3)
    at Gue.checkDirStatus (C:\Users\rodolfo\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:113:10)
    at Gue.writeComponent (C:\Users\rodolfo\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:35:10)
    at Gue.generate (C:\Users\rodolfo\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:27:10)
    at Object.<anonymous> (C:\Users\rodolfo\AppData\Roaming\npm\node_modules\vue-gue\src\bin.js:21:9)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT'
}

**Comment by mohamadsdf** [comment]
> mkdir bar
> 
> > mkdir bar
> > gue foo ./bar
> 
> Error: ENOENT: no such file or directory, mkdir at Object.mkdirSync (fs.js:823:3) at Gue.checkDirStatus (C:\Users\rodolfo\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:113:10) at Gue.writeComponent (C:\Users\rodolfo\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:35:10) at Gue.generate (C:\Users\rodolfo\AppData\Roaming\npm\node_modules\vue-gue\src\index.js:27:10) at Object. (C:\Users\rodolfo\AppData\Roaming\npm\node_modules\vue-gue\src\bin.js:21:9) at Module._compile (internal/modules/cjs/loader.js:959:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) at Module.load (internal/modules/cjs/loader.js:815:32) at Function.Module._load (internal/modules/cjs/loader.js:727:14) at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) { errno: -4058, syscall: 'mkdir', code: 'ENOENT' }

i think this problem is on windows os 
are you using windows ?
